version: '3.8'

services:
  #properties database
  properties-db:
    image: postgres:17
    container_name: properties-db
    environment:
      POSTGRES_DB: properties
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456._.Samar
    ports:
      - "5433:5432"
    volumes:
      - properties_data:/var/lib/postgresql/data

  #users database
  users-db:
    image: postgres:17
    container_name: users-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456._.Samar
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  #config-server Microservice
  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"

  #discovery Microservice
  discovery:
    build:
      context: ./discovery
    depends_on:
      - config-server
    ports:
      - "8761:8761"

  #gateway Microservice
  gateway:
    build:
      context: ./gateway-service
    depends_on:
      - config-server
    ports:
      - "8222:8222"

  #loan Microservice
  loans:
    build:
      context: ./loan
    depends_on:
      - config-server
      - properties-db
    environment:
      DB_URL: jdbc:postgresql://properties-db:5432/properties
      DB_USER: postgres
      DB_PASSWORD: 123456._.Samar
    ports:
      - "8092:8092"

  #property Microservice
  property:
    build:
      context: ./property
    depends_on:
      - config-server
      - properties-db
    environment:
      DB_URL: jdbc:postgresql://properties-db:5432/properties
      DB_USER: postgres
      DB_PASSWORD: 123456._.Samar
    ports:
      - "8091:8091"

  #user-auth Microservice
  user-auth:
    build:
      context: ./user-auth
    depends_on:
      - config-server
      - users-db
    environment:
      DB_URL: jdbc:postgresql://users-db:5432/users
      DB_USER: postgres
      DB_PASSWORD: 123456._.Samar
    ports:
      - "8090:8090"

volumes:
  properties_data:
  users_data:
