eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
server:
  port: 8091

spring:
  application:
    name: properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    loans-url: http://localhost:8092/api/v1/loans