server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false
